version: '2.3'

services:
  codingracing:
    build: application
    restart: always

  nginx:
    image: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    depends_on:
      - codingracing
    volumes:
      - ./nginx/certs:/certs/:ro
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./application:/var/www/:ro
      - ./nginx/logs:/var/log/nginx

